### ISSUE TITLE
binary tree code using c

### ISSUE THREAD

**Issue by saicharan1901** [saicharan1901/datastructures#14]

**Comment by Pragya2056** [comment]
I will work on it.

**Comment by Pragya2056** [comment]
The issue was worked on #16

**Comment by saicharan1901** [comment]
thanks for working on it Pragya would love to collab in the future as I'm a
frontend developer

**Comment by Pragya2056** [comment]
Sure

**Comment by Pragya2056** [comment]
You can close this issue now.
